DATA:
  TRAIN: ('mnist',)
  TEST: ('mnist',)
  NUM_CLASSES: 10
  PATH: './datasets/MNIST'
  DATA_DIR: './datasets/MNIST'
LOSS:
  LOSS: 'xentropy'
DATALOADER:
  BSZ: 128
  RE: 'no'
  WORKERS: 4
OPTIM:
  OPT: 'qhm'
  LR: 1.0
  MOM: 0.9
  NU: 1.0
  WD: 0.0
  EPOCHS: 300
  WARMUP: 0
  DROP_FREQ: 50
  DROP_FACTOR: 10.0
  VAL: 0
  ADAM:
    BETA1: 0.9
    BETA2: 0.999
  SASA:
    LEAK_RATIO: 4
    SIGNIF: 0.05
    N: 400
    DELTA: 0.02
    MODE: 'olbm'
    LOGSTATS: 10
    TESTS_PER_EPOCH: 1
  LS:
    GAMMA: 0.05
    SDC: 0.05
    INC: 2.0
    DEC: 0.5
    MAX: 2
    IGN: 0
    EVAL: 1
    DIR: 'g'
    COS: 0
MODEL:
  ARCH: "mylinear"
  NONLINEARITY: "celu"
  MODEL_PATH: ""
  PRETRAINED: False
OUTPUT_DIR: "/tmp"
BACKUP_LOG_DIR: ""
LOG_FREQ: 10
EVALUATE: False
ONLY_SAVE_LAST: 0